/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package barberia;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Usuario
 */
public class ListaDePrecios1 extends javax.swing.JFrame {
    static ArrayList<String> servicios = new ArrayList<>();
    static int precio = 0;
    String hora= "";
    SpinnerNumberModel modeloSpinnerHora = new SpinnerNumberModel();
    MenuUsuario1 confirmarCita;
    /**
     * Creates new form ListaDePrecios1
     */
    public ListaDePrecios1() {

        initComponents();
        setLocationRelativeTo(null);
        setTitle("Por favor escoja un servicio");
        modeloSpinnerHora = new SpinnerNumberModel();
        modeloSpinnerHora.setMinimum(0);
        modeloSpinnerHora.setMaximum(12);

        
        jSpinner1.setModel(modeloSpinnerHora);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox62 = new javax.swing.JCheckBox();
        jCheckBox64 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox65 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(java.awt.Color.darkGray);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Servicios de cortes:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 90, 140, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("▼ Lista de Precios Classic Cuts ▼");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 290, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Servicios de Cabello (Chicas):");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 87, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Servicios de Uñas:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 87, 152, 27));

        jCheckBox1.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox1.setText("Tapper Fade: 22,000$");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 190, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox2.setText("Low Fade: 25,000$");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 216, 142, -1));

        jCheckBox3.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox3.setText("Classic: 12,000$");
        jCheckBox3.setName("va"); // NOI18N
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 138, 142, -1));

        jCheckBox4.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox4.setText("Mullet: 15,000$");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 164, 142, -1));

        jCheckBox5.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox5.setText("BuzzCut: 17,000$");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 242, 142, -1));

        jCheckBox6.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox6.setText("Mohicano: 20,000$");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 294, 142, -1));

        jCheckBox7.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox7.setText("Seventh: 20,000$");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 268, 142, -1));

        jCheckBox8.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox8.setText("Cuadricular: 18,000$");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jCheckBox9.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox9.setText("             Manicure: 20,000$");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 138, 220, -1));

        jCheckBox10.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox10.setText("            Pedicure: 25,000$");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 164, 220, -1));

        jCheckBox11.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox11.setText("Combo tradicional: 40,000$");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 190, 220, -1));

        jCheckBox13.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox13.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox13.setText("Semi-permanentes (Manos): 45,000$");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 216, -1, -1));

        jCheckBox14.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox14.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox14.setText("Semi-permanentes (Pies): 50,000$");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 242, 220, -1));

        jCheckBox16.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox16.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox16.setText("Combo Semi-permanente: 90,000$");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jCheckBox18.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox18.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox18.setText("           Manos Press On: 75,000$");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 220, -1));

        jCheckBox19.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox19.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox19.setText("            Esmaltado Acrilico: 100,000$");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jCheckBox12.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox12.setText("Blw.corto: 25,000$");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 134, 160, -1));

        jCheckBox15.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox15.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox15.setText("Blw.mediano:35,000$");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 166, 160, -1));

        jCheckBox22.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox22.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox22.setText("Blw.largo: 50,000$");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 198, 160, -1));

        jCheckBox23.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox23.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox23.setText("   Keratina: 250,000$");
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 226, 160, -1));

        jCheckBox24.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox24.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox24.setText("      Tinte: 250,000$");
        jCheckBox24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox24ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 160, -1));

        jCheckBox62.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox62.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox62.setText("Cejas: 10,000$");
        jCheckBox62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox62ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox62, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 134, 129, -1));

        jCheckBox64.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox64.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox64.setText("Masaje: 40,000$");
        jCheckBox64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox64ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox64, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 166, 129, -1));

        jLabel7.setBackground(new java.awt.Color(255, 51, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Servicios Adicionales:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 148, -1));

        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Listo!");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 167, 44));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hora:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 203, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DD/MM/AAAA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, -1));

        jCheckBox65.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox65.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox65.setText("Pestañas: 25,000$");
        jCheckBox65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox65ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox65, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 198, 129, -1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        jButton1.setText("Cerrar Sesion.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        jCheckBox25.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox25.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox25.setText("Barba: 10,000$");
        jCheckBox25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox25ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 230, 129, -1));

        jCheckBox26.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox26.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox26.setText("Aminoacido: 200,000$");
        jCheckBox26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox26ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 292, 160, -1));

        jCheckBox17.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox17.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox17.setText("Personalizado: 25,000$");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jCheckBox20.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox20.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox20.setText("           Sistema Deeping: 70,000$");
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 220, -1));

        jCheckBox27.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox27.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCheckBox27.setText("Iluminaciones: 220,000$");
        jCheckBox27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox27ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 324, -1, -1));

        jButton3.setText("Ver mis reservas.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            addServicio("Tapper Fade",22000);
        }else{
            deleteServicio("Tapper Fade", 22000);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected()){
            addServicio("Low Fade",25000);
        }else{
            deleteServicio("Low Fade", 25000);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(jCheckBox3.isSelected()){
            addServicio("Classic",12000);
        }else{
            deleteServicio("Classic", 12000);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        if(jCheckBox4.isSelected()){
            addServicio("Mullet",15000);
        }else{
            deleteServicio("Mullet", 15000);
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if(jCheckBox5.isSelected()){
            addServicio("Buzz Cut",17000);
        }else{
            deleteServicio("Buzz Cut", 17000);
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        if(jCheckBox6.isSelected()){
            addServicio("Mohicano",20000);
        }else{
            deleteServicio("Mohicano", 20000);
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        if(jCheckBox7.isSelected()){
            addServicio("Seventh",20000);
        }else{
            deleteServicio("Seventh", 20000);
        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        if(jCheckBox8.isSelected()){
            addServicio("Cuadricular",18000);
        }else{
            deleteServicio("Cuadricular", 18000);
        }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        if(jCheckBox9.isSelected()){
            addServicio("Manicure",20000);
        }else{
            deleteServicio("Manicure", 20000);
        }
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        if(jCheckBox10.isSelected()){
            addServicio("Pedicure",25000);
        }else{
            deleteServicio("Pedicure", 25000);
        }
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        if(jCheckBox11.isSelected()){
            addServicio("Combo Tradicional",40000);
        }else{
            deleteServicio("Combo Tradicional", 40000);
        }
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        if(jCheckBox13.isSelected()){
            addServicio("Semi-permanentes (Manos)",45000);
        }else{
            deleteServicio("Semi-permanentes (Manos)", 45000);
        }
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        if(jCheckBox14.isSelected()){
            addServicio("Semi-permanentes (Pies)",50000);
        }else{
            deleteServicio("Semi-permanentes (Pies)", 50000);
        }
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        if(jCheckBox16.isSelected()){
            addServicio("Combo Semi-Permanente",90000);
        }else{
            deleteServicio("Combo Semi-Permanente", 90000);
        }
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
        if(jCheckBox18.isSelected()){
            addServicio("Manos Press On",75000);
        }else{
            deleteServicio("Manos Press On", 75000);
        }
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
        if(jCheckBox19.isSelected()){
            addServicio("Esmaltado Acrilico",100000);
        }else{
            deleteServicio("Esmaltado Acrilico", 100000);
        }
    }//GEN-LAST:event_jCheckBox19ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        if(jCheckBox12.isSelected()){
            addServicio("Blw corto",25000);
        }else{
            deleteServicio("Blw corto", 25000);
        }
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        if(jCheckBox15.isSelected()){
            addServicio("Blw mediano",35000);
        }else{
            deleteServicio("Blw mediano", 35000);
        }
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        if(jCheckBox22.isSelected()){
            addServicio("Blw largo",50000);
        }else{
            deleteServicio("Blw largo", 50000);
        }
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox23ActionPerformed
        if(jCheckBox23.isSelected()){
            addServicio("Keratina",250000);
        }else{
            deleteServicio("Keratina", 250000);
        }
    }//GEN-LAST:event_jCheckBox23ActionPerformed

    private void jCheckBox24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox24ActionPerformed
        if(jCheckBox24.isSelected()){
            addServicio("Tinte",250000);
        }else{
            deleteServicio("Tinte", 250000);
        }
    }//GEN-LAST:event_jCheckBox24ActionPerformed

    private void jCheckBox62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox62ActionPerformed
        if(jCheckBox62.isSelected()){
            addServicio("Cejas",10000);
        }else{
            deleteServicio("Cejas",10000);
        }
    }//GEN-LAST:event_jCheckBox62ActionPerformed

    private void jCheckBox64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox64ActionPerformed
        if(jCheckBox64.isSelected()){
            addServicio("Masaje",40000);
        }else{
            deleteServicio("Masaje", 40000);
        }
    }//GEN-LAST:event_jCheckBox64ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        confirmarCita = new MenuUsuario1();
        int horascroll = (int) modeloSpinnerHora.getValue();
        if(jTextField1.getText().matches("^([0-2][0-9]|3[0-1])(\\/|-)(0[1-9]|1[0-2])\\2(\\d{4})$")&&horascroll>0&&horascroll<13&&precio!=0){
            confirmarCita.setFecha(jTextField1.getText());
            hora = horascroll+":00 "+ jComboBox1.getSelectedItem();
            confirmarCita.setHora(hora);
            confirmarCita.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Por favor, rellene todos los campos.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox65ActionPerformed
        if(jCheckBox65.isSelected()){
            addServicio("Pestañas",25000);
        }else{
            deleteServicio("Pestañas", 25000);
        }
    }//GEN-LAST:event_jCheckBox65ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JOptionPane.showMessageDialog(null, "¿Esta seguro que quiere cerrar sesion?");
                int ae = JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere cerrar sesion?","Cierre de sesion", JOptionPane.YES_NO_OPTION);
                
                if(ae==JOptionPane.YES_OPTION){
                    Barberia.cerrarSesion(this);
                    if(confirmarCita.isVisible()){confirmarCita.dispose();}
                    servicios.clear();
                    precio = 0;
                }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox25ActionPerformed
        if(jCheckBox25.isSelected()){
            addServicio("barba",10000);
        }else{
            deleteServicio("barba", 10000);
        }                                     
    }//GEN-LAST:event_jCheckBox25ActionPerformed

    private void jCheckBox26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox26ActionPerformed
         if(jCheckBox64.isSelected()){
            addServicio("Aminoacido",200000);
        }else{
            deleteServicio("Aminoacido", 200000);
        }                                          

    }//GEN-LAST:event_jCheckBox26ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
         if(jCheckBox17.isSelected()){
            addServicio("Corte Personalizado",25000);
        }else{
            deleteServicio("Corte Personalizado", 25000);
        }                                          
       
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
       if(jCheckBox20.isSelected()){
            addServicio("Sistema Deeping",70000);
        }else{
            deleteServicio("Sistema Deeing", 70000);
        }                                          
        
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox27ActionPerformed
       if(jCheckBox27.isSelected()){
            addServicio("Iluminaciones",220000);
        }else{
            deleteServicio("Iluminaciones",220000);
        }                                         
    }//GEN-LAST:event_jCheckBox27ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                VerCitas1 a = new VerCitas1();
                a.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    public void addServicio(String servicio,int precios){
        if(servicios.isEmpty()){
            servicios.add(servicio);
            precio+=precios;
        }
        if (!servicios.contains(servicio)) {
            servicios.add(servicio);
            precio += precios;
        }
    }
    public void deleteServicio(String servicio,int precios){
        precio-=precios;
        for(int i=0;i<servicios.size();i++){
            if(servicios.get(i).equals(servicio)){
                servicios.remove(i);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox62;
    private javax.swing.JCheckBox jCheckBox64;
    private javax.swing.JCheckBox jCheckBox65;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
