@startuml
annotation java.lang.SuppressWarnings
class barberia.Barberia
class barberia.Bienvenidoa1
class barberia.Cita
class barberia.Cliente
class barberia.Empleado
class barberia.HistorialAdministrador1
class barberia.ListaDePrecios1
class barberia.MenuEmpleado1
class barberia.MenuUsuario1
class barberia.RegistroInicio1
class barberia.VerCitas1
class java.io.BufferedReader
class java.io.BufferedWriter
class java.io.File
class java.io.FileReader
class java.io.FileWriter
class java.io.IOException
class java.text.ParseException
class java.text.SimpleDateFormat
class java.time.LocalDateTime
class java.time.format.DateTimeFormatter
class java.util.ArrayList
class java.util.Date
class java.util.List
class java.util.logging.Level
class java.util.logging.Logger
class javax.swing.ImageIcon
class javax.swing.JButton
class javax.swing.JFrame
class javax.swing.JLabel
class javax.swing.JOptionPane
class javax.swing.SpinnerNumberModel
class javax.swing.table.DefaultTableModel
barberia.Barberia ..> java.util.List
barberia.Barberia ..> javax.swing.JFrame
barberia.Bienvenidoa1 ..> java.lang.SuppressWarnings
barberia.Bienvenidoa1 ..> javax.swing.ImageIcon
barberia.Bienvenidoa1 --|> javax.swing.JFrame
barberia.Cita ..> java.io.BufferedReader
barberia.Cita ..> java.io.BufferedWriter
barberia.Cita ..> java.io.File
barberia.Cita ..> java.io.FileReader
barberia.Cita ..> java.io.FileWriter
barberia.Cita ..> java.io.IOException
barberia.Cita ..> java.util.ArrayList
barberia.Cita ..> java.util.List
barberia.Cliente ..> java.io.BufferedReader
barberia.Cliente ..> java.io.BufferedWriter
barberia.Cliente ..> java.io.File
barberia.Cliente ..> java.io.FileReader
barberia.Cliente ..> java.io.FileWriter
barberia.Cliente ..> java.io.IOException
barberia.Cliente ..> java.util.ArrayList
barberia.Cliente ..> java.util.List
barberia.Empleado ..> java.io.BufferedReader
barberia.Empleado ..> java.io.BufferedWriter
barberia.Empleado ..> java.io.File
barberia.Empleado ..> java.io.FileReader
barberia.Empleado ..> java.io.FileWriter
barberia.Empleado ..> java.io.IOException
barberia.Empleado ..> java.util.ArrayList
barberia.Empleado ..> java.util.List
barberia.HistorialAdministrador1 ..> java.lang.SuppressWarnings
barberia.HistorialAdministrador1 ..> javax.swing.ImageIcon
barberia.HistorialAdministrador1 --|> javax.swing.JFrame
barberia.HistorialAdministrador1 ..> javax.swing.table.DefaultTableModel
barberia.ListaDePrecios1 ..> java.lang.SuppressWarnings
barberia.ListaDePrecios1 ..> java.text.ParseException
barberia.ListaDePrecios1 ..> java.text.SimpleDateFormat
barberia.ListaDePrecios1 ..> java.time.LocalDateTime
barberia.ListaDePrecios1 ..> java.time.format.DateTimeFormatter
barberia.ListaDePrecios1 ..> java.util.ArrayList
barberia.ListaDePrecios1 ..> java.util.Date
barberia.ListaDePrecios1 ..> java.util.logging.Level
barberia.ListaDePrecios1 ..> java.util.logging.Logger
barberia.ListaDePrecios1 ..> javax.swing.ImageIcon
barberia.ListaDePrecios1 --|> javax.swing.JFrame
barberia.ListaDePrecios1 ..> javax.swing.JOptionPane
barberia.ListaDePrecios1 ..> javax.swing.SpinnerNumberModel
barberia.MenuEmpleado1 ..> java.lang.SuppressWarnings
barberia.MenuEmpleado1 ..> javax.swing.ImageIcon
barberia.MenuEmpleado1 --|> javax.swing.JFrame
barberia.MenuEmpleado1 ..> javax.swing.table.DefaultTableModel
barberia.MenuUsuario1 ..> java.lang.SuppressWarnings
barberia.MenuUsuario1 ..> javax.swing.ImageIcon
barberia.MenuUsuario1 --|> javax.swing.JFrame
barberia.MenuUsuario1 ..> javax.swing.JOptionPane
barberia.RegistroInicio1 ..> java.lang.SuppressWarnings
barberia.RegistroInicio1 ..> java.text.ParseException
barberia.RegistroInicio1 ..> java.util.logging.Level
barberia.RegistroInicio1 ..> java.util.logging.Logger
barberia.RegistroInicio1 ..> javax.swing.ImageIcon
barberia.RegistroInicio1 ..> javax.swing.JButton
barberia.RegistroInicio1 --|> javax.swing.JFrame
barberia.RegistroInicio1 ..> javax.swing.JLabel
barberia.RegistroInicio1 ..> javax.swing.JOptionPane
barberia.VerCitas1 ..> java.lang.SuppressWarnings
barberia.VerCitas1 ..> javax.swing.ImageIcon
barberia.VerCitas1 --|> javax.swing.JFrame
barberia.VerCitas1 ..> javax.swing.table.DefaultTableModel
@enduml